name: 'TS Blockchain'

on: push

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Install Node'
        uses: actions/setup-node@v1
        with:
          node-version: 15.11.0

      - name: Install dependencies
        run: | 
          npm install

      - name: Run Tests
        run: |
          npm test